//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotationSolver.SourceGenerators.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotationSolver.SourceGenerators.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using RotationSolver.Basic.Actions;
        ///
        ///namespace RotationSolver.Basic.Rotations;
        ///
        ////// &lt;summary&gt;
        ////// The Custom Rotation.
        ////// &lt;br&gt;Number of Actions: 48&lt;/br&gt;
        ////// &lt;/summary&gt;
        ///public abstract partial class CustomRotation
        ///{
        ///#region Actions
        ///    private readonly Lazy&lt;IBaseAction&gt; _SprintPvECreator = new(() =&gt; 
        ///    {
        ///        IBaseAction action = new BaseAction((ActionID)3, false);
        ///        CustomRotation.LoadActionSetting(ref action);
        ///    
        ///        var setting = action.Setting;
        ///        ModifySprintPvE(r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Autoattack = 1,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Spell = 2,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Weaponskill = 3,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Ability = 4,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Item = 5,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///DoLAbility = 6,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///DoHAbility = 7,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Event = 8,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///LimitBreak = 9,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///System = 10,
        ////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionCategory {
            get {
                return ResourceManager.GetString("ActionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#action/3&quot;&gt;&lt;strong&gt;Sprint&lt;/strong&gt;&lt;/see&gt; &lt;i&gt;PvE&lt;/i&gt; (All Classes) [3] [System]
        ////// &lt;para&gt;&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///SprintPvE = 3,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#action/5&quot;&gt;&lt;strong&gt;Teleport&lt;/strong&gt;&lt;/see&gt; &lt;i&gt;PvE&lt;/i&gt; (All Classes) [5] [System]
        ////// &lt;para&gt;&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///TeleportPvE = 5,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#action/6&quot;&gt;&lt;strong&gt;Return&lt;/strong&gt;&lt;/see&gt; &lt;i&gt;PvE&lt;/i&gt; (All Classes) [6] [Sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionId {
            get {
                return ResourceManager.GetString("ActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///DutyRoulette = 1,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Dungeons = 2,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Guildhests = 3,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Trials = 4,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Raids = 5,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///PvP = 6,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///QuestBattles = 7,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///FatEs = 8,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///TreasureHunt = 9,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Levequests = 10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using RotationSolver.Basic.Actions;
        ///
        ///namespace RotationSolver.Basic.Rotations.Duties;
        ///
        ////// &lt;summary&gt;
        ////// The Custom Rotation.
        ////// &lt;br&gt;Number of Actions: 388&lt;/br&gt;
        ////// &lt;/summary&gt;
        ///public abstract partial class DutyRotation
        ///{
        ///    private readonly Lazy&lt;IBaseAction&gt; _MagitekCannonPvECreator = new(() =&gt; 
        ///    {
        ///        IBaseAction action = new BaseAction((ActionID)1128, true);
        ///        CustomRotation.LoadActionSetting(ref action);
        ///    
        ///        var setting = action.Setting;
        ///        ModifyMagitekCannon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DutyAction {
            get {
                return ResourceManager.GetString("DutyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OpCode {
            get {
                return ResourceManager.GetString("OpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ECommons.DalamudServices;
        ///using ECommons.ExcelServices;
        ///using RotationSolver.Basic.Actions;
        ///using RotationSolver.Basic.Traits;
        ///
        ///namespace RotationSolver.Basic.Rotations.Basic;
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://na.finalfantasyxiv.com/jobguide/paladin&quot;&gt;&lt;strong&gt;Paladin&lt;/strong&gt;&lt;/see&gt;
        ////// &lt;br&gt;Number of Actions: 46&lt;/br&gt;
        ////// &lt;br&gt;Number of Traits: 15&lt;/br&gt;
        ////// &lt;/summary&gt;
        ///[Jobs(Job.PLD, Job.GLA)]
        ///public abstract partial class PaladinRotation : CustomRotation
        ///{
        ///    static PLDGauge JobGauge =&gt; S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#status/1&quot;&gt;&lt;strong&gt;Petrification&lt;/strong&gt;&lt;/see&gt; ↓ (All Classes)
        ////// &lt;para&gt;Stone-like rigidity is preventing the execution of actions.&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///Petrification = 1,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#status/2&quot;&gt;&lt;strong&gt;Stun&lt;/strong&gt;&lt;/see&gt; ↓ (All Classes)
        ////// &lt;para&gt;Unable to execute actions.&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///Stun = 2,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#status/3&quot;&gt;&lt;strong&gt;Sleep&lt;/strong&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusId {
            get {
                return ResourceManager.GetString("StatusId", resourceCulture);
            }
        }
    }
}
