//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotationSolver.SourceGenerators.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotationSolver.SourceGenerators.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ActionCategory {
            get {
                return ResourceManager.GetString("ActionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#action/1&quot;&gt;&lt;strong&gt;Key Item&lt;/strong&gt;&lt;/see&gt; &lt;i&gt;PvE&lt;/i&gt; (All Classes)
        ////// &lt;para&gt;&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///KeyItem = 1,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#action/2&quot;&gt;&lt;strong&gt;Interaction&lt;/strong&gt;&lt;/see&gt; &lt;i&gt;PvE&lt;/i&gt; (All Classes)
        ////// &lt;para&gt;&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///Interaction = 2,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#action/3&quot;&gt;&lt;strong&gt;Sprint&lt;/strong&gt;&lt;/see&gt; &lt;i&gt;PvE&lt;/i&gt; (All Classes)
        ////// &lt;para&gt;&lt;/para&gt;
        ////// &lt;/summa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionId {
            get {
                return ResourceManager.GetString("ActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///DutyRoulette = 1,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Dungeons = 2,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Guildhests = 3,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Trials = 4,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Raids = 5,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///PvP = 6,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///QuestBattles = 7,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///FatEs = 8,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///TreasureHunt = 9,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Levequests = 10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#status/1&quot;&gt;&lt;strong&gt;Petrification&lt;/strong&gt;&lt;/see&gt; ↓ (All Classes)
        ////// &lt;para&gt;Stone-like rigidity is preventing the execution of actions.&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///Petrification = 1,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#status/2&quot;&gt;&lt;strong&gt;Stun&lt;/strong&gt;&lt;/see&gt; ↓ (All Classes)
        ////// &lt;para&gt;Unable to execute actions.&lt;/para&gt;
        ////// &lt;/summary&gt;
        ///Stun = 2,
        ////// &lt;summary&gt;
        ////// &lt;see href=&quot;https://garlandtools.org/db/#status/3&quot;&gt;&lt;strong&gt;Sleep&lt;/strong&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusId {
            get {
                return ResourceManager.GetString("StatusId", resourceCulture);
            }
        }
    }
}
